# Site settings
title: "Data+AI Academy"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:
address: V4 Complex, Uttarahalli Main Rd, Simhadri layout, Uttarahalli Hobli, Bengaluru, Karnataka 560061
phone_number: +919353003282
email: enroll@dataplusai.academy
whatapp_message: "Hello, I am interested in learning more about DataPlusAI Academy courses and trainings."
g_form: https://forms.gle/33fP2SVgTijNKz8S8
map_link: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.0254146620364!2d77.54189989999999!3d12.9060873!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae3f0031408bc1%3A0xc249cd5523b6223f!2sData%2BAI%20Academy!5e0!3m2!1sen!2sin!4v1739437259634!5m2!1sen!2sin
collections:
  courses:
    output: true
    permalink: /courses/:path/

# Build settings
markdown: kramdown
