# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/dataplusaiacademy/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

phone_number: +919353003282
email: enroll@dataplusai.academy
g_form: https://forms.gle/33fP2SVgTijNKz8S8

collections:
  courses:
    output: true
    permalink: /courses/:path/

# Build settings
markdown: kramdown
