# Site settings
title: "Data+AI Academy"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Contact Information
phone_number: +919353016950
email: enroll@dataplusai.academy
whatapp_message: "Hello, I am interested in learning more about DataPlusAI Academy courses and trainings."
g_form: https://forms.gle/33fP2SVgTijNKz8S8

# North Bengaluru (Primary)
address_north: 232, 9th Main Rd, HRBR Layout 1st Block, 1st Block, Kalyan Nagar, Bengaluru, Karnataka 560043
map_link_north: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.2869853938646!2d77.64750310000001!3d13.0173877!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae17cad9024d6b%3A0x3a7df12843a5dc3e!2s43%20Workspace!5e0!3m2!1sen!2sin!4v1759756095271!5m2!1sen!2sin

# South Bengaluru
address_south: V4 Complex, Uttarahalli Main Rd, Simhadri layout, Uttarahalli Hobli, Bengaluru, Karnataka 560061
map_link_south: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.0254146620364!2d77.54189989999999!3d12.9060873!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae3f0031408bc1%3A0xc249cd5523b6223f!2sData%2BAI%20Academy!5e0!3m2!1sen!2sin!4v1739437259634!5m2!1sen!2sin
collections:
  courses:
    output: true
    permalink: /courses/:path/

seo:
  meta_og_title: "Data+AI Academy"
  meta_og_type: "website"
  meta_og_url: "https://dataplusai.academy/"
  meta_og_image: "https://dataplusai.academy/img/data-plus-ai.svg"
  meta_og_description: "Practitioner-led learning program focussed on building real-time data streaming platforms and applications."
  meta_twitter_card: "summary"
  meta_twitter_site: "@dataplusai"
  meta_twitter_creator: "@dataplusai"

# Build settings
markdown: kramdown
